name: health_history
description: A new Flutter project.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:       # CRITICAL: Required for every Flutter project - DO NOT REMOVE
    sdk: flutter # CRITICAL: Required for every Flutter project - DO NOT REMOVE
  
  # CRITICAL: Core UI and responsive design - DO NOT REMOVE OR MODIFY
  sizer: ^2.0.15              # Required for responsive design system
  flutter_svg: ^2.0.9        # Required for SVG icon support
  google_fonts: ^6.1.0       # Required for typography (replaces local fonts)
  shared_preferences: ^2.2.2 # Required for local data storage
  web: ^1.1.1
  
  # Feature dependencies - safe to modify
  cached_network_image: ^3.3.1
  connectivity_plus: ^6.1.4
  dio: ^5.4.0
  fluttertoast: ^8.2.4
  fl_chart: ^0.65.0           # For medication adherence tracking charts and data visualization
  smooth_page_indicator: ^1.2.1
  permission_handler: ^11.1.0 # For camera and storage permissions
  camera: ^0.10.5+5           # For real camera integration with document scanning
  image_picker: ^1.0.4
  image_cropper: ^9.1.0
  record: ^6.0.0              # For real audio recording functionality
  file_picker: ^8.1.7
  path_provider: ^2.1.2
  universal_html: ^2.2.4
  flutter_slidable: ^4.0.1
  syncfusion_flutter_pdfviewer: ^29.1.38
  supabase_flutter: ^2.10.2   # For Supabase integration
  flutter_local_notifications: ^18.0.1  # For smart reminders and notifications
  share_plus: ^10.1.0         # For sharing secure links
  qr_flutter: ^4.1.0          # For QR code generation
  crypto: ^3.0.5              # For secure access code generation
  cross_file: ^0.3.3+8        # For cross-platform file handling
  timezone: ^0.9.2            # For timezone support in notifications
  mobile_scanner: ^7.1.2      # For QR code scanning functionality

dev_dependencies:
  flutter_test:    # CRITICAL: Required for Flutter project testing - DO NOT REMOVE
    sdk: flutter   # CRITICAL: Required for Flutter project testing - DO NOT REMOVE
  flutter_lints: ^5.0.0 # CRITICAL: Required for code quality - DO NOT REMOVE

flutter:
  uses-material-design: true # CRITICAL: Required for Material icon font - DO NOT REMOVE
  assets:
    - assets/
    - assets/images/
    - env.json
  # CRITICAL ASSET MANAGEMENT RULES:
  # - DO NOT ADD NEW ASSET DIRECTORIES (assets/svg/, assets/icons/, etc.)
  # - ONLY USE EXISTING AND ITEMS AVAILABLE IN THE DIRECTORIES LISTED ABOVE (assets/, assets/images/)
  
  # CRITICAL FONTS RULE: 
  # - THIS PROJECT USES GOOGLE FONTS INSTEAD OF LOCAL FONTS
  # - DO NOT ADD ANY LOCAL FONTS SECTION OR FONT FILES

# Environment Variables Required:
# - SUPABASE_URL: Your Supabase project URL
# - SUPABASE_ANON_KEY: Your Supabase anonymous key
